Tester/Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }
        [Required]
        public string BowlerLastName { get; set; }
        [Required]
        public string BowlerFirstName { get; set; }
        public char? BowlerMiddleInit { get; set; }
        [Required]
        public string BowlerAddress { get; set; }
        [Required]
        public string BowlerCity { get; set; }
        [Required]
        public string BowlerState { get; set; }
        [Required]
        public string BowlerZip { get; set; }
        [Required]
        [Phone]
        public string BowlerPhoneNumber { get; set; }
        [Required]
        public int TeamID { get; set; }
        public Team Team { get; set; }
    }
}

Tester/Models/BowlerDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Models
{
    public class BowlerDbContext : DbContext
    {
        public BowlerDbContext(DbContextOptions<BowlerDbContext> options) : base(options)
        {

        }
        public DbSet<Bowler> Bowlers { get; set; }
        public DbSet<Team> Teams { get; set; }
    }
}

Tester/Models/EFBowlerRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Models
{
    public class EFBowlerRepository : IBowlerRepository
    {
        private BowlerDbContext _context { get; set; }
        public EFBowlerRepository(BowlerDbContext temp)
        {
            _context = temp;
        }
        public IQueryable<Bowler> Bowlers => _context.Bowlers;

        public IQueryable<Team> Teams => _context.Teams;

        public void SaveBowler(Bowler b)
        {
            _context.Update(b);
            _context.SaveChanges();
        }
        public void CreateBowler(Bowler b)
        {
            _context.Add(b);
            _context.SaveChanges();
        }
        public void DeleteBowler(Bowler b)
        {
            _context.Remove(b);
            _context.SaveChanges();
        }
    }
}

Tester/Models/IBowlerRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Models
{
    public interface IBowlerRepository
    {
        IQueryable<Bowler> Bowlers { get; }
        IQueryable<Team> Teams { get; }
        void SaveBowler(Bowler b);
        void CreateBowler(Bowler b);
        void DeleteBowler(Bowler b);
    }
}

Tester/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int CaptainID { get; set; }

    }
}

Tester/Components/TeamsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Tester.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tester.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private IBowlerRepository repo { get; set; }
        public TeamsViewComponent(IBowlerRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            //send team info and route data so that it works
            ViewBag.SelectedType = RouteData?.Values["team"];
            var teams = repo.Teams.Select(x => x.TeamName);
            return View("Default", teams);
        }
    }
}

Tester/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tester.Models;

namespace Tester.Controllers
{
    public class HomeController : Controller
    {
        //set up repository
        private IBowlerRepository _repo;

        public HomeController(IBowlerRepository temp)
        {
            _repo = temp;
        }

        //index
        public IActionResult Index(string team)
        {
            ViewBag.IsIndex = true;
            var teams = _repo.Teams.ToList();
            //get list of bowlers according to selected team, or all if none is selected
            var thing = _repo.Bowlers
                .Where(b => b.Team.TeamName == team || team == null).ToList();

            //used to set header
            if (team != null)
            {
                ViewBag.Selected = team;
            }
            return View(thing);
        }

        [HttpPost]
        public IActionResult Index(int BowlerID)
        {
            //deletes bowler when submitted
            var bowler = _repo.Bowlers.Where(x => x.BowlerID == BowlerID).FirstOrDefault();
            _repo.DeleteBowler(bowler);
            return RedirectToAction("Index", "");
        }

        public IActionResult EditBowlers(int BowlerID = 0)
        {
            Bowler b = new Bowler();
            //if it is not 0, it is an edit form
            if (BowlerID != 0)
            {
                //get correct bowler
                b = _repo.Bowlers.Where(x => x.BowlerID == BowlerID).FirstOrDefault();
                ViewBag.IsEdit = true;
            }
            //otherwise, we are creating a new bowler
            else
            {
                ViewBag.IsEdit = false;
            }
            ViewBag.Teams = _repo.Teams.Distinct().ToList();
            return View(b);
        }
        [HttpPost]
        public IActionResult EditBowlers(Bowler b)
        {
            if (ModelState.IsValid)
            {
                if (b.BowlerID != 0)
                {
                    //update bowler
                    _repo.SaveBowler(b);
                }
                else
                {
                    //create new bowler
                    //autoincrementing wasnt working so this is the work around
                    int max = _repo.Bowlers.OrderByDescending(x => x.BowlerID).First().BowlerID + 1;
                    b.BowlerID = max;
                    _repo.CreateBowler(b);
                }
                return RedirectToAction("Index");
            }
            //stuff to return model errors
            if (b.BowlerID != 0)
            {
                ViewBag.IsEdit = true;
            }
            else
            {
                ViewBag.IsEdit = false;
            }
            ViewBag.Teams = _repo.Teams.Distinct().ToList();
            return View(b);
        }

    }
}

Tester/Views/Home/EditBowlers.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit";
}

@model Bowler
@if (!ViewBag.IsEdit)
{
    <h2 class="text-center">Create New Bowler</h2>
}
else
{
    <h2 class="text-center">Edit Bowler</h2>
}

<div class="d-flex flex-column align-items-center">
    <div class="text-danger" asp-validation-summary="All"></div>
    <form class="mx-5" method="post" action="EditBowlers">
        <div style="display:grid; grid-template-columns: 1fr 1.25fr; grid-template-rows: auto; grid-row-gap: 1rem; grid-column-gap: 2rem;">
            <input type="hidden" asp-for="@Model.BowlerID" />
            <span>First Name</span>
            <input type="text" asp-for="@Model.BowlerFirstName" class="form-select" />
            <span>Middle Initial</span>
            <input type="text" asp-for="@Model.BowlerMiddleInit" class="form-select" />
            <span>Last Name</span>
            <input type="text" asp-for="@Model.BowlerLastName" class="form-select" />
            <span>Address</span>
            <input type="text" asp-for="@Model.BowlerAddress" class="form-select" />
            <span>City</span>
            <input type="text" asp-for="@Model.BowlerCity" class="form-select" />
            <span>State</span>
            <input type="text" asp-for="@Model.BowlerState" class="form-select" />
            <span>Zip</span>
            <input type="text" asp-for="@Model.BowlerZip" class="form-select" />
            <span>Phone Number</span>
            <input type="text" asp-for="@Model.BowlerPhoneNumber" class="form-select" />
            <span>Team</span>
            <select asp-for="@Model.TeamID" class="form-control">
                @foreach (var t in ViewBag.Teams)
                {
                    <option value="@t.TeamID">@t.TeamName</option>
                }
            </select>
        </div>
        <div class="d-flex justify-content-center mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>

Tester/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<Bowler>
@if(ViewBag.Selected != null)
            {
                <h2 class="text-center">@ViewBag.Selected</h2>
            }
<a class="btn btn-primary text-center mb-3 text-white" asp-action="EditBowlers" asp-route-BowlerID="">Create New Bowler</a>
<table class="table table-bordered table-striped">
    <thead class="thead-dark">
        <tr>
            <th>First Name</th>
            <th>Middle Initial</th>
            <th>Last Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Phone Number</th>
            <th>Team</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Bowler b in Model)
        {
            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>
                <td>@b.Team.TeamName</td>
                <td class="d-flex">
                    <a class="btn btn-primary text-white mr-2" asp-action="EditBowlers" asp-route-BowlerID="@b.BowlerID">Edit</a>
                    <form method="post" action="Index" id="@b.BowlerID">
                        <input type="hidden" name="BowlerID" value="@b.BowlerID" />
                        <button type="button" class="btn btn-danger text-white" onclick="if (confirm('Are you sure you want to delete this bowler?') == true) { document.getElementById('@b.BowlerID').submit(); } ">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

Tester/Views/Shared/Components/Teams/Default.cshtml
@{

}
@model IEnumerable<string>
<div class="d-grid gap-2">
    <a asp-controller="Home" asp-action="Index" asp-route-team="" class="btn btn-outline-secondary">Home</a><br />
    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-team="@t" class="btn @(ViewBag.SelectedType == t ? "btn-primary" : "btn-outline-secondary")">@t</a><br />
    }
</div>

Tester/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tester</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Bowlers DB</div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        @if (ViewBag.IsIndex != null)
        {
        <div id="types" class="col-3">
            <vc:teams></vc:teams>
        </div>
        }
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>